apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: "mystcls"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: myclaim
  gcePersistentDisk:
    pdName: my-data-disk-2
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi