# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pred
  template:
    metadata:
      labels:
        app: ml-pred
    spec:
      containers:
        - name: ml-model-predictor
          image: ML_PREDICTION_IMAGE
          volumeMounts:
            - mountPath: "/mnt/c"
              name: test-volume
          ports:
          - containerPort: 8080
      volumes:
        - name: test-volume
          # This GCE PD must already exist.
          persistentVolumeClaim:
            claimName: myclaim
---
apiVersion: v1
kind: Service
metadata:
  name: ml-pred
spec:
  type: LoadBalancer
  selector:
    app: ml-pred
  ports:
    - port: 80
      targetPort: 8080
